In [2]:
import numpy as np
import pandas as pd

data = pd.read_csv("Datasets/matches - matches.csv")

In [3]:
#masking
mask = data['city']=='Hyderabad' # Boolean series
data[mask].head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN

In [4]:
# Function to find number of matches in each city

def get_city_match_count(city):
    mask = data['city'] == city
    return data[mask].shape[0]

print(get_city_match_count('Pune'))
print(get_city_match_count('Mumbai'))
print(get_city_match_count('Kolkata'))
print(get_city_match_count('Bangalore'))

32
85
61
66

In [5]:
#Multiple conditions

mask1 = data['city'] == 'Mumbai'
mask2 = data['date'] > '2010-01-01'
data[mask1 & mask2].head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
15,16,2017,Mumbai,2017-04-16,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN

In [6]:
def get_match_count_city_year(city, date):
    mask1 = data['city'] == city
    mask2 = data['date'] > date
    return data[mask1 & mask2].shape[0]

print(get_match_count_city_year('Mumbai', '2015-01-01'))
print(get_match_count_city_year('Bangalore', '2015-01-01'))
print(get_match_count_city_year('Chennai', '2015-01-01'))

23
24
7

**The value_counts method**

In [7]:
# Freequency count of data in a particular column
# This is generally used only on categorical columns

data['winner'].value_counts()

Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: winner, dtype: int64